catalogs:
  list:
    "@rslib/core": ^0.6.3
    "@rspack/core": ^1.3.5
    "@swc/helpers": ~0.5.17
    "@types/node": ^18
    react: 19.0.0
    react-native: 0.79.1
    terser-webpack-plugin: ^5.3.14
    testers:
      react-native-test-app: 4.3.3
    typescript: ^5.8.3
    webpack: ^5.99.5

nodeLinker: node-modules

#winLinkType: "junctions" | "symlinks"
winLinkType: "symlinks"

patchFolder: ./patches

plugins:
  - checksum: 4cb9601cfc0c71e5b0ffd0a85b78e37430b62257040714c2558298ce1fc058f4e918903f0d1747a4fef3f58e15722c35bd76d27492d9d08aa5b04e235bf43b22
    path: .yarn/plugins/@yarnpkg/plugin-catalogs.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-catalogs/main/bundles/%40yarnpkg/plugin-catalogs.js"
